services:
  database:
    container_name: database
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    container_name: redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  rabbit:
    container_name: rabbit
    image: rabbitmq:4.1
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  springshop:
    container_name: springshop
    env_file: .env
    image: ${API_IMAGE}:${API_IMAGE_VERSION}
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy

volumes:
  postgres_data:
      driver: local
  redis_data:
      driver: local
  rabbit_data:
      driver: local
