spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
