spring:
  application:
    name: springshop
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  mvc:
    log-resolved-exception: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
